spring:
  application:
   name: api-gateway

server:
  port: 8080


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    fetch-registry: true
    register-with-eureka: true


#api-gateway -configuration

##here we are defining routes

## user - service
  cloud:
    gateway:
      routes:
        - id: "user service"
          uri: "lb://user service"
          predicates:
            - "Path=/user/**"




